bc_dataset:
  _target_: read_data.p3po_xarm.BCDataset
  path: ${root_dir}/expert_demos/xarm_env
  processed_path: '${root_dir}/processed_data'
  tasks: ${suite.task.tasks}
  num_demos_per_task: ${num_demos_per_task}
  obs_type: ${obs_type}
  history: ${suite.history}
  history_len: ${suite.history_len}
  prompt: ${prompt}
  temporal_agg: ${temporal_agg}
  num_queries: ${num_queries}
  img_size: 128
  action_after_steps: ${suite.action_after_steps}
  intermediate_goal_step: 30
  store_actions: true
  training_keys: ${training_keys}
  subsample: 5
  skip_first_n: 0
  relative_actions: true
