name: p3po
channels:
  - defaults
dependencies:
  - python=3.9
  - pip #=24.0
  - numpy #=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
  - llvm-openmp #=19.1.0
  - pip:
    - pre-commit
    - black
    - PyOpenGL-accelerate
    - protobuf==3.20.1
    - termcolor==1.1.0
    - gym==0.22.0
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0
    - ipdb==0.13.9
    - yapf==0.31.0
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56
    - sentence-transformers
    - einops==0.7.0
    - decord
    - mujoco==2.3.7
    - dm_control
    - diffusers==0.15.0
    - ipywidgets
    - ipycanvas
    - accelerate
    - torch
    - torchvision
    - torchaudio
    - wheel
    - setuptools
    - ninja
    - robomimic
