# @package agent
_target_: agent.rt1.RT1Agent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
hidden_dim: ${suite.hidden_dim}
stddev_schedule: 0.1
stddev_clip: 0.3
use_tb: ${use_tb}
augment: True
obs_type: ${obs_type}
pixel_keys: ${suite.pixel_keys}
proprio_key: ${suite.proprio_key}
feature_key: ${suite.feature_key}
use_proprio: ${use_proprio}
norm: false
history: ${suite.history}
history_len: ${suite.history_len}
eval_history_len: ${suite.eval_history_len}
use_language: ${use_language}
prompt: ${prompt}
film: true
